// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkKSn9RPBVbeg7Fk9OTA9Pd0Y3jdexZzY',
    appId: '1:614014335445:web:44f9839ea76c9c32c8655c',
    messagingSenderId: '614014335445',
    projectId: 'task-management-66d65',
    authDomain: 'task-management-66d65.firebaseapp.com',
    storageBucket: 'task-management-66d65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeC1Rt-a5ggUJBFmUWK3Fk-A_7RPAXGuw',
    appId: '1:614014335445:android:c5995799a5fc48b7c8655c',
    messagingSenderId: '614014335445',
    projectId: 'task-management-66d65',
    storageBucket: 'task-management-66d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi9O6QZM0yGr4i9ROIZpsLuSMrQH5Kn08',
    appId: '1:614014335445:ios:712b21ba2bceff09c8655c',
    messagingSenderId: '614014335445',
    projectId: 'task-management-66d65',
    storageBucket: 'task-management-66d65.appspot.com',
    iosClientId: '614014335445-mk6iqrfjgfunrghod41rjs0p58d23ien.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskMangment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi9O6QZM0yGr4i9ROIZpsLuSMrQH5Kn08',
    appId: '1:614014335445:ios:712b21ba2bceff09c8655c',
    messagingSenderId: '614014335445',
    projectId: 'task-management-66d65',
    storageBucket: 'task-management-66d65.appspot.com',
    iosClientId: '614014335445-mk6iqrfjgfunrghod41rjs0p58d23ien.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskMangment',
  );
}
